#!/usr/bin/env python3
# ============================================================
# Generate a per-challenge post-layout (R+C PEX) testbench for the
# arbchain macro. One launch pulse per run, so every measured node
# has exactly ONE rising crossing (all .meas are RISE=1 - the
# multi-crossing RISE=n searches are what hung ngspice before).
#
# Probes (from chain_map.json):
#   tT01..tT16  top[g] chain nodes  (mux output-transistor terminal)
#   tB01..tB16  bot[g] chain nodes
#   wA0T/wA1T/wA0B/wA1B  gate-side fragments (wire vs cell split)
#   tDpin/tGpin dlrtp_1 input pins  (last-stage wire contribution)
#   tq          q rising crossing;  qval = v(q) sampled at 45 ns
#
# Nodes that appear ONLY in capacitor lines (floating metal islands
# in the hand-drawn GDS) make the DC solve singular; each one gets a
# 1 T-ohm bleed resistor to ground (electrically invisible, makes the
# matrix solvable).
#
# Usage:
#   python3 gen_postsim_tb.py --map chain_map.json --pex arbchain_pex.spice \
#       --pdk <PDKPATH> --challenge 0000 --out postsim_0000.spice
# ============================================================

import argparse
import json
import re


def floating_cap_nodes(pex_path):
    """Nodes touched exclusively by C elements (no X/R)."""
    cap_nodes, wired = set(), set()
    for raw in open(pex_path):
        line = raw.strip()
        if not line or line.startswith("*"):
            continue
        c0 = line[0]
        if c0 in "Cc":
            tok = line.split()
            cap_nodes.update(tok[1:3])
        elif c0 in "XxRrVvIi":
            tok = line.split()
            wired.update(tok[1:5] if c0 in "Xx" else tok[1:3])
    return sorted(cap_nodes - wired - {"0", "VPWR", "VGND"})


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--map", required=True)
    ap.add_argument("--pex", required=True)
    ap.add_argument("--pdk", required=True, help="path containing sky130A")
    ap.add_argument("--challenge", required=True,
                    help="16-bit challenge, 4 hex digits (e.g. 0000)")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    ch_bits = int(args.challenge, 16)
    if not 0 <= ch_bits <= 0xFFFF:
        raise SystemExit("challenge must be a 16-bit value (4 hex digits)")
    amap = json.load(open(args.map))

    L = []
    w = L.append
    w(f"* arbchain post-layout sim (R+C PEX), challenge 0x{args.challenge}")
    w("* generated by src/macro/sim/gen_postsim_tb.py - do not edit")
    w("*")
    w("* one launch pulse (10-50 ns); all .meas are RISE=1 crossings")
    w(f"* ch bits set: {[i for i in range(16) if (ch_bits >> i) & 1]}")
    w("")
    w(f".lib {args.pdk}/libs.tech/ngspice/sky130.lib.spice tt")
    w(f".include {args.pex}")
    w("")
    w("* ---- supplies ----")
    w("Vdd VPWR 0 1.8")
    w("Vss VGND 0 0")
    w("")
    w("* ---- challenge (static for this run) ----")
    for i in range(16):
        w(f"Vc{i} ch[{i}] 0 {'1.8' if (ch_bits >> i) & 1 else '0'}")
    w("")
    w("* ---- reset low 5 ns, launch pulse 10-50 ns ----")
    w("Vrst arb_rst_n 0 PWL(0 0 5n 0 5.02n 1.8 200n 1.8)")
    w("Vl launch 0 PWL(0 0 10n 0 10.02n 1.8 50n 1.8 50.02n 0 200n 0)")
    w("")
    w("* ---- output load (controller arb_q input pin) ----")
    w("Cload q 0 10f")
    w("")

    islands = floating_cap_nodes(args.pex)
    if islands:
        w("* ---- bleed resistors for floating metal islands ----")
        for k, n in enumerate(islands):
            w(f"Risland{k} {n} 0 1e12")
        w("")

    w(".tran 2p 75n")
    w("")
    w(".control")
    w("run")
    for g in range(1, 17):
        e = amap["stages"][g - 1]
        w(f"meas tran tT{g:02d} WHEN v({e['top_probe']})=0.9 RISE=1")
        w(f"meas tran tB{g:02d} WHEN v({e['bot_probe']})=0.9 RISE=1")
    for g, e in enumerate(amap["stages"]):
        for k in ("top_a0_gate", "top_a1_gate", "bot_a0_gate", "bot_a1_gate"):
            net = e[k]
            tag = ("T" if k.startswith("top") else "B") + k[4:6].upper()
            w(f"meas tran w{tag}{g:02d} WHEN v({net})=0.9 RISE=1")
    arb = amap["arbiter"]
    w("meas tran tL WHEN v(launch)=0.9 RISE=1")
    w(f"meas tran tDpin WHEN v({arb['d_pin']})=0.9 RISE=1")
    w(f"meas tran tGpin WHEN v({arb['gate_pin']})=0.9 RISE=1")
    w("meas tran tq WHEN v(q)=0.9 RISE=1")
    w("* q is captured at the GATE falling edge (~launch fall + chain delay);")
    w("* sample AFTER it - during transparency q just follows D")
    w("meas tran q55 FIND v(q) AT=55n")
    w("meas tran q60 FIND v(q) AT=60n")
    w("meas tran q62 FIND v(q) AT=62n")
    w("meas tran q63 FIND v(q) AT=63n")
    w("meas tran q64 FIND v(q) AT=64n")
    w("meas tran q65 FIND v(q) AT=65n")
    w("meas tran q70 FIND v(q) AT=70n")
    w("meas tran qfall WHEN v(q)=0.9 FALL=1")
    w("meas tran qval FIND v(q) AT=70n")
    w("* falling-edge arrivals (discharge skew) + slew reference")
    w(f"meas tran fDpin WHEN v({arb['d_pin']})=0.9 FALL=1")
    w(f"meas tran fGpin WHEN v({arb['gate_pin']})=0.9 FALL=1")
    w(f"meas tran fD50 WHEN v({arb['d_pin']})=0.5 FALL=1")
    w(f"meas tran fG50 WHEN v({arb['gate_pin']})=0.5 FALL=1")
    w("quit")
    w(".endc")
    w(".end")

    with open(args.out, "w") as f:
        f.write("\n".join(L) + "\n")
    print(f"wrote {args.out} ({len(islands)} floating islands bled, "
          f"{16 * 2 + len(amap['stages']) * 4 + 3} meas)")


if __name__ == "__main__":
    main()
